2024-10-05 23:53:27,773 | INFO | START BOT
2024-10-05 23:53:27,997 | INFO | Bot: IMGAi [@imagesAI_bot]
2024-10-05 23:53:28,156 | WARNING | Updates were skipped successfully.
2024-10-05 23:53:28,156 | INFO | Start polling.
2024-10-05 23:53:34,176 | WARNING | User 678552784 is register
2024-10-05 23:57:49,637 | INFO | START generation image
2024-10-05 23:57:49,736 | INFO | There are still requests left - 20
2024-10-05 23:57:59,799 | INFO | There are still requests left - 19
2024-10-05 23:58:09,849 | INFO | There are still requests left - 18
2024-10-05 23:58:09,973 | INFO | Successfully generate generic_photo_user/678552784/cat.png
2024-10-06 00:00:33,333 | INFO | The image cat.png was saved successfully
2024-10-06 00:05:44,958 | INFO | Menu Settings: user 678552784
2024-10-06 00:07:34,089 | INFO | Setting the style: user 678552784
2024-10-06 00:09:08,712 | INFO | SET NEGATIVE PROMPT: user 678552784
2024-10-06 00:11:08,067 | INFO | Bact to main menu: user 678552784
2024-10-06 00:11:09,979 | INFO | User 678552784 scans files
2024-10-06 00:13:24,372 | INFO | User 678552784 open file cat.png
2024-10-06 00:13:29,008 | INFO | File cat.png downloaded successfully User: 678552784
2024-10-06 00:18:41,447 | INFO | Open like image User: 678552784
2024-10-06 00:19:04,314 | INFO | Like is set image cat.png User: 678552784
2024-10-06 00:23:16,202 | WARNING | Add ERROR User 678552784
2024-10-06 00:24:47,570 | INFO | INFO about bot User 678552784
2024-10-06 00:47:43,264 | ERROR | Cause exception while getting updates.
Traceback (most recent call last):
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiohttp\client.py", line 586, in _request
    await resp.start(conn)
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiohttp\client_reqrep.py", line 920, in start
    self._continue = None
  File "D:\Рабочий стол\Urban University\DIPLOM_project\.venv\lib\site-packages\aiohttp\helpers.py", line 725, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2024-10-06 01:01:40,766 | INFO | GET First place User 678552784
2024-10-06 01:06:58,521 | INFO | User 678552784 enter to admin panel
2024-10-06 01:08:59,699 | INFO | User 908892108 successfully add to admin panel
2024-10-06 01:11:22,152 | INFO | User 908892108 was deleted
2024-10-06 01:12:33,454 | INFO | Stop polling...
2024-10-06 01:12:33,454 | WARNING | Goodbye!
